### ISSUE TITLE
The problem about random crop.

### ISSUE THREAD

**Issue by NirvanaMyth** [BowenL0218/MMVC_video_codec#1]
Thank you for sharing your excellent work!
However, I have a problem about random crop.
In dataset.py, the transform.RandomCrop() is used for cropping the vimeo dataset. But an error occured when I trained the Optical Flow Conditioned Feature Prediction mode with the vimeo dataset:

Traceback (most recent call last):
  File "train_new_model_vimeo.py", line 292, in <module>
    test(global_step)
  File "train_new_model_vimeo.py", line 114, in test
    for batch_idx, (prev1, prev2, prev3, prev4, cur) in enumerate(test_loader):
  File "/home/customer/.conda/envs/MMVC/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/customer/.conda/envs/MMVC/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 557, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/customer/.conda/envs/MMVC/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/customer/.conda/envs/MMVC/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/customer/lp/MMVC_video_codec-main/datasets_vimeo.py", line 125, in __getitem__
    Concat = transform(Concat)
  File "/home/customer/.conda/envs/MMVC/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 49, in __call__
    img = t(img)
  File "/home/customer/.conda/envs/MMVC/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 421, in __call__
    i, j, h, w = self.get_params(img, self.size)
  File "/home/customer/.conda/envs/MMVC/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 394, in get_params
    w, h = img.size
TypeError: 'builtin_function_or_method' object is not iterable

It looks like the cropped image is not iterable. How to solve this error?

**Comment by YY-RR-ZZ** [comment]
> Thank you for sharing your excellent work! However, I have a problem about random crop. In dataset.py, the transform.RandomCrop() is used for cropping the vimeo dataset. But an error occured when I trained the Optical Flow Conditioned Feature Prediction mode with the vimeo dataset:
> 
> Traceback (most recent call last): File "train_new_model_vimeo.py", line 292, in test(global_step) File "train_new_model_vimeo.py", line 114, in test for batch_idx, (prev1, prev2, prev3, prev4, cur) in enumerate(test_loader): File "/home/customer/.conda/envs/MMVC/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 517, in **next** data = self._next_data() File "/home/customer/.conda/envs/MMVC/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 557, in _next_data data = self._dataset_fetcher.fetch(index) # may raise StopIteration File "/home/customer/.conda/envs/MMVC/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "/home/customer/.conda/envs/MMVC/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in data = [self.dataset[idx] for idx in possibly_batched_index] File "/home/customer/lp/MMVC_video_codec-main/datasets_vimeo.py", line 125, in **getitem** Concat = transform(Concat) File "/home/customer/.conda/envs/MMVC/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 49, in **call** img = t(img) File "/home/customer/.conda/envs/MMVC/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 421, in **call** i, j, h, w = self.get_params(img, self.size) File "/home/customer/.conda/envs/MMVC/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 394, in get_params w, h = img.size TypeError: 'builtin_function_or_method' object is not iterable
> 
> It looks like the cropped image is not iterable. How to solve this error?

Sorry to bother you. I'd like to ask you about the Code implementation of this paper. Regarding the code currently released by the authors, is it true that only the implementation based on convLSTM for the prediction of features in the four modes has been published, and the other modes based on optical flow, skip model, and feature propagation are not included yet?
